import {z} from 'zod';
import {repository,RESOURCES,querySchema,taskChangesSchema,parisDate,filterTasks,isComplete,reportEvidence} from './nexora.mts';
export function registerNexoraTools(s,scope,db,uid){
 const repo=repository(db,uid),read={readOnlyHint:true,openWorldHint:false},write={readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false};
 const id=z.string().min(1).max(200),key=z.string().min(1).max(500),version=z.string().length(64);
 const emit=data=>({content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data});
 const add=(name,description,inputSchema,annotations,fn)=>s.registerTool(name,{description,inputSchema,annotations},async args=>{try{return emit(await fn(args));}catch(e){return {isError:true,content:[{type:'text',text:e.message||'Nexora operation failed'}]};}});
 if(scope.includes('nexora:read')){
  add('get_google_calendar_import_config','Lire les calendriers Google sélectionnés dans gcalSettings, leurs projets existants, la fenêtre civile Europe/Paris et configVersion. Aucun secret ni jeton. Utiliser le connecteur Google Calendar pour lire les événements, avec pagination.',{},read,()=>repo.googleCalendarConfig());
  add('list_projects','Lister les projets, statuts, types, responsables et définitions de champs personnalisés Nexora. ACTION correspond au type Tâches si aucun type ACTION explicite ne figure au catalogue.',{},read,async()=>({ok:true,catalogs:await repo.catalogs()}));
  add('list_tasks','Rechercher toutes les tâches par texte, projet, statut, type, responsable, identifiant Gmail/Drive, échéance ou période. Bornes de dates inclusives Europe/Paris. dateField=end pour les échéances, overlap pour les réunions du jour, completedAt pour les tâches effectivement terminées. Parcourir nextCursor jusqu’à null. detail=full inclut descriptions, checklists, pièces jointes et champs personnalisés.',querySchema,read,a=>repo.list(a));
  add('list_meetings','Rechercher les réunions dont le type est explicitement Réunion/Réunions, avec descriptions, participants, checklists et liens. Une description ne prouve pas la présence d’un compte rendu : consulter reportEvidence. Une pièce jointe liée doit être lue avec son connecteur avant d’en résumer le contenu.',querySchema,read,a=>repo.list({...a,meetingsOnly:true,detail:'full'}));
  add('get_task','Lire intégralement une tâche ou réunion active ou archivée, avec version pour les modifications sans écrasement concurrent.',{taskId:id},read,a=>repo.get(a.taskId));
  add('get_summary','Calculer des compteurs exhaustifs sur une période, les échéances, retards, tâches terminées et réunions. Les listes sont limitées explicitement ; utiliser list_tasks/list_meetings avec pagination pour une synthèse exhaustive. Ne jamais inventer un compte rendu absent.',{dateFrom:z.string().date().optional(),dateTo:z.string().date().optional(),projectId:id.optional(),limit:z.number().int().min(1).max(100).default(30)},read,async a=>{
   const from=a.dateFrom||parisDate(),to=a.dateTo||from;if(from>to)throw new Error('Invalid date range');const d=await repo.taskSnapshot('all'),c=Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v.value])),all=repo.selected(d,'all'),active=all.filter(t=>!t._archived),base={projectId:a.projectId,dateFrom:from,dateTo:to};
   const groups={due:filterTasks(active,c,{...base,dateField:'end'}),overdue:active.filter(t=>(!a.projectId||t.projectId===a.projectId)&&t.end&&t.end.slice(0,10)<from&&!isComplete(t,c.statuses)),completed:filterTasks(all,c,{...base,dateField:'completedAt'}),meetings:filterTasks(all,c,{...base,dateField:'overlap',meetingsOnly:true})};
   return {ok:true,timezone:'Europe/Paris',generatedAt:new Date().toISOString(),dateFrom:from,dateTo:to,counts:Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,v.length])),groups:Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,{total:v.length,truncated:v.length>a.limit,tasks:v.slice(0,a.limit).map(t=>repo.enrich(t,c,k==='meetings'))}])),reportCoverage:{meetings:groups.meetings.length,withExplicitReport:groups.meetings.filter(t=>reportEvidence(t,c.customFieldDefs).length).length},notes:['due signifie échéance, completed signifie completedAt renseigné.','Les réunions sont identifiées par leur type explicite, jamais leur titre.','Une description libre peut contenir des notes ou un ordre du jour ; ne pas la présenter automatiquement comme un compte rendu.']};
  });
  add('get_health','Vérifier une lecture authentifiée réelle des données Nexora, les compteurs, révisions et la disponibilité des outils MCP.',{},read,async()=>{const d=await repo.taskSnapshot('all');return {ok:true,authenticated:true,mode:'firebase-admin-mcp',version:'1.0.2',timezone:'Europe/Paris',date:parisDate(),counts:Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v.value.length])),revisions:Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v.revision])),scope};});
  add('get_activity','Lire l’historique Nexora et les opérations du MCP sur une période, pour récapituler ce qui a été créé ou modifié. L’historique de l’application peut être limité ; ne pas présenter cette liste comme l’ensemble des événements passés.',{dateFrom:z.string().date(),dateTo:z.string().date(),limit:z.number().int().min(1).max(200).default(100)},read,async a=>{
   if(a.dateFrom>a.dateTo)throw new Error('Invalid date range');const log=await repo.read('activityLog');
   const userEvents=log.value.filter(x=>{const at=x.at||x.createdAt;if(!at)return false;const day=parisDate(at);return day>=a.dateFrom&&day<=a.dateTo;});
   const lower=new Date(a.dateFrom+'T00:00:00Z');lower.setUTCDate(lower.getUTCDate()-1);const upper=new Date(a.dateTo+'T00:00:00Z');upper.setUTCDate(upper.getUTCDate()+2);
   const snap=await db.collection('users').doc(uid).collection('nexora_mcp_operations').where('createdAt','>=',lower.toISOString()).where('createdAt','<',upper.toISOString()).orderBy('createdAt','desc').limit(1000).get();
   const events=snap.docs.map(x=>x.data()).filter(x=>{const day=parisDate(x.createdAt);return day>=a.dateFrom&&day<=a.dateTo;}).map(x=>({at:x.createdAt,type:x.operation,taskId:x.result.taskId||x.result.task?.id||null,title:x.result.task?.title||null,resource:x.result.resource||null,source:'mcp'}));
   const all=[...userEvents.map(x=>({...x,source:'application'})),...events].sort((a,b)=>String(b.at).localeCompare(String(a.at)));
   return {ok:true,dateFrom:a.dateFrom,dateTo:a.dateTo,count:all.length,events:all.slice(0,a.limit),truncated:all.length>a.limit||snap.size===1000,coverage:'Journal applicatif conservé et opérations MCP ; pas un historique complet garanti.'};
  });
  add('list_resources','Découvrir les domaines Nexora disponibles en lecture/écriture : projets, catalogues, équipes, risques, budgets, dépenses, échéances, tableaux de bord et réglages. Les historiques et états de synchronisation sont en lecture seule ; taskBaselines (plan initial) n\'accepte que replace_settings, avec des entrées {start,end,capturedAt} en AAAA-MM-JJ fusionnées aux existantes ; aucune opération Google Calendar ou Budget360.',{},read,async()=>({ok:true,resources:RESOURCES,readOnly:['activityLog','momentumSnapshots','workflowExecutionLog','gcalSyncState'],settingsOnly:['taskBaselines'],taskTools:['create_task','update_task','complete_task','archive_task','restore_task','delete_task'],excluded:['Identifiants et secrets de connexion','Modification de Google Calendar','Transactions Budget360']}));
  add('read_resource','Lire un domaine Nexora avec ses champs exacts et sa révision. Paginer avec nextOffset. Lire avant toute modification, préserver les champs non concernés.',{resource:z.enum(RESOURCES),id:id.optional(),query:z.string().optional(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(100).default(50)},read,a=>repo.readResource(a));
 }
 if(scope.includes('nexora:write')){
  const eventTime=z.object({date:z.string().date().optional(),dateTime:z.string().datetime({offset:true}).optional(),timeZone:z.string().optional()}).strict();
  add('import_google_calendar_events','Importer au plus 50 événements réellement lus avec Google Calendar. Utiliser get_google_calendar_import_config, transmettre le calendarId exact et configVersion ; observer les sources depuis moins d’une heure. Préserve les IDs Nexora, les identifiants Google, notes personnelles et archives. Une annulation Google explicite archive la tâche ; une absence ne supprime rien. Dates de fin all-day Google exclusives. Aucun accès ni écriture Google depuis cet outil. Relire chaque taskId retourné. Réutiliser idempotencyKey lors des réessais.',{calendarId:id,configVersion:version,observedAt:z.string().datetime({offset:true}),idempotencyKey:key,events:z.array(z.object({id:id,status:z.enum(['confirmed','tentative','cancelled']).optional(),summary:z.string().max(10000).optional(),description:z.string().max(100000).optional(),location:z.string().max(10000).optional(),start:eventTime.optional(),end:eventTime.optional(),updated:z.string().datetime({offset:true}).optional(),recurringEventId:id.optional(),originalStartTime:eventTime.optional()}).strict()).max(50)},write,a=>repo.importGoogleCalendar(a));
  add('create_task','Créer une tâche ou réunion Nexora avec tous ses champs, descriptions, sources Gmail/Drive, pièces jointes, checklist, responsable et dates explicites. Résoudre le catalogue d’abord ; réutiliser idempotencyKey en cas de réessai. Dates obligatoires pour tous les types : une date fournie complète l’autre ; sinon date de réception du mail si transmise, puis date d’exécution Europe/Paris. Déduplique les clés et sources déjà présentes, y compris les tâches archivées.',{...taskChangesSchema.shape,title:z.string().min(1).max(240),projectId:id,idempotencyKey:key},write,a=>repo.createTask(a));
  add('update_task','Modifier les champs demandés d’une tâche/réunion en préservant les autres. Début et fin ne peuvent rester vides ; repli sur la date fournie, la réception du mail ou la date d’exécution Europe/Paris. expectedVersion vient de get_task. Les listes fournies remplacent leur champ : relire et fusionner avant modification. Utiliser add_attachment pour ajouter un lien sans écraser les pièces jointes.',{taskId:id,expectedVersion:version,idempotencyKey:key,changes:taskChangesSchema},write,a=>repo.mutateTask(a));
  for(const [name,action,description] of [['complete_task','complete','Terminer une tâche (progression 100 et statut Terminé).'],['archive_task','archive','Archiver une tâche de façon réversible.'],['restore_task','restore','Restaurer une tâche archivée.']])add(name,description+' Lire get_task avant écriture et fournir sa version.',{taskId:id,expectedVersion:version,idempotencyKey:key},write,a=>repo.mutateTask(a,action));
  add('delete_task','Supprimer définitivement une tâche déjà archivée, uniquement sur demande explicite de suppression définitive de l’utilisateur.',{taskId:id,expectedVersion:version,idempotencyKey:key,confirmPermanentDeletion:z.literal(true)},{...write,destructiveHint:true},a=>repo.mutateTask(a,'delete'));
  add('add_attachment','Ajouter un lien de document à une tâche, sans écraser ses pièces jointes. Déduplique par URL et documentId. Ne télécharge ni ne partage le document.',{taskId:id,expectedVersion:version,idempotencyKey:key,documentId:id.optional(),attachment:z.object({id:id.optional(),type:z.literal('link').default('link'),provider:z.string().default('google-drive'),driveKind:z.enum(['file','folder']).optional(),documentId:id.optional(),name:z.string().min(1),url:z.string().url().refine(x=>new URL(x).protocol==='https:')}).strict()},write,a=>repo.mutateTask(a,'add_attachment'));
  add('save_meeting_report','Ajouter un compte rendu explicite à la description d’une réunion, en préservant les notes existantes. Contenu fourni par l’utilisateur ou synthèse des sources effectivement lues. Aucune déduction d’une réunion tenue depuis sa seule date.',{taskId:id,expectedVersion:version,idempotencyKey:key,report:z.string().min(1).max(60000)},write,a=>repo.mutateTask(a,'save_meeting_report'));
  add('mutate_resource','Créer/modifier/supprimer une entité Nexora ou mettre à jour des réglages. Lire read_resource avant et fournir expectedRevision ; changes fusionne les champs de premier niveau. Les listes imbriquées remplacent leur champ. Ne pas modifier les catalogues verrouillés ni supprimer une entité encore référencée. Toute suppression exige une demande explicite. taskBaselines n\'accepte que replace_settings : chaque entrée {start,end,capturedAt} est validée puis fusionnée, les tâches absentes du lot gardent leur baseline.',{resource:z.enum(RESOURCES),action:z.enum(['create','update','delete','replace_settings']),id:id.optional(),changes:z.record(z.unknown()).optional(),expectedRevision:z.string().nullable(),idempotencyKey:key},{...write,destructiveHint:true},a=>repo.mutateResource(a));
 }
}
