import test from 'node:test';
import assert from 'node:assert/strict';
import {registerBudgetTools} from '../src/budget.mts';
// Outils Budget (#587) : enregistrés selon le scope, appels de l'API Nexora
// avec la clé de l'assistant (simulée ici), politique de confirmation gardée.
function setup(scope){const tools=new Map(),calls=[];const s={registerTool:(name,def,fn)=>tools.set(name,{def,fn})};registerBudgetTools(s,scope,async(path,method='GET',body=null)=>{calls.push({path,method,body});return {ok:true,path};});return {tools,calls};}
test('scopes : lecture seule sans écriture, écriture seule sans lecture',()=>{assert.deepEqual([...setup(['nexora:read']).tools.keys()],['get_budget_summary','search_budget_transactions']);assert.deepEqual([...setup(['nexora:write']).tools.keys()],['categorize_budget_transaction']);assert.equal(setup(['nexora:read']).tools.get('get_budget_summary').def.annotations.readOnlyHint,true);});
test('synthèse et recherche : routes /api/finance en GET, filtres en paramètres',async()=>{const {tools,calls}=setup(['nexora:read','nexora:write']);await tools.get('get_budget_summary').fn({});await tools.get('get_budget_summary').fn({month:'2026-09'});await tools.get('search_budget_transactions').fn({query:'Café crème',dateFrom:'2026-09-01',minAmount:0,limit:50,offset:0});assert.deepEqual(calls.map(c=>[c.path,c.method]),[['/api/finance/budget-summary','GET'],['/api/finance/budget-summary?month=2026-09','GET'],['/api/finance/transactions/search?query=Caf%C3%A9+cr%C3%A8me&dateFrom=2026-09-01&minAmount=0&limit=50&offset=0','GET']]);});
test('catégorisation : PATCH /api/finance/transactions, confirmation laissée à la politique serveur',async()=>{const {tools,calls}=setup(['nexora:write']);await tools.get('categorize_budget_transaction').fn({transactionId:'t1',category:'Alimentation',subcategory:'Courses',confirmed:false,idempotencyKey:'k1'});assert.deepEqual(calls[0],{path:'/api/finance/transactions',method:'PATCH',body:{transactionId:'t1',category:'Alimentation',subcategory:'Courses',confirmed:false,idempotencyKey:'k1',allowAutoCommit:true}});assert.match(tools.get('categorize_budget_transaction').def.description,/accord explicite/);});
test('erreur de l\'API rendue comme erreur d\'outil, sans exception',async()=>{const tools=new Map();registerBudgetTools({registerTool:(n,d,fn)=>tools.set(n,fn)},['nexora:read'],async()=>{throw new Error('Nexora API 400 invalid_month');});const r=await tools.get('get_budget_summary')({month:'2026-09'});assert.equal(r.isError,true);assert.match(r.content[0].text,/invalid_month/);});
